# Headless services host: core (not base) + dev (podman) + server, plus the
# shared shell. No desktop stack.
_: {
  imports = [
    ../../modules/nixos/core
    ../../modules/nixos/dev
    ../../modules/nixos/server
    ./hardware.nix
    ./hardware/hardware-configuration.nix # generated by nixos-anywhere at install (see INSTALL.md)
  ];

  networking.hostName = "home-server";
  system.stateVersion = "25.05";

  home-manager.users.maudi.imports = [
    ../../modules/home/cli
    ../../modules/home/neovim
  ];

  # Forgejo Actions runner. Both the UUID here and `forgejo-runner-token` in
  # secrets/home-server/forgejo.yaml are issued by the forge when the runner is
  # created in its admin UI, and are only valid for *that* forge — a rebuilt
  # instance mints new ones and both must be replaced together (INSTALL.md §5).
  # Forgejo itself is always on.
  services.forgejoRunner = {
    enable = true;
    uuid = "1e25f307-13c8-4119-94b2-9ad8072de161";
  };

  # SSH is key-only (PasswordAuthentication is off in modules/nixos/server/ssh.nix),
  # so the admin's public key must be enrolled here. Replace the placeholder.
  users.users.maudi.openssh.authorizedKeys.keys = [
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAm+h4JjyhM3plsb2UFpq4FuaFvy00uzVr3fpYWVnALH maudi@desktop"
  ];
}
